### ISSUE TITLE
Disables mouse input?

### ISSUE THREAD

**Issue by jdclifton2** [LucasBr003/camera-2d-plus#1]
Hi,

I am attempting to use your plug in, but it seems like it disables input from the mouse when I add it. I suspect that this is because of the layers you are adding but I can't figure out how to fix it. 

It also seems to be related to the fact that I am trying to put it inside of a Control node (TextureRect). I have already tried setting mouse filter to ignore on the TextureRect.

Thanks

**Comment by SuperMatCat24** [comment]
Increasing the layer on the canvaslayer you want to have input worked for me. 
![image](https://github.com/LucasBr003/camera-2d-plus/assets/79697349/3a038699-8852-43fd-9c85-1416e68e73e3)
